/*
 Ajax DataGrid
 Version: 1.1.0
 (c) 2011 DMXzone.com
 @build 01-12-2011 13:40:43
*/
(function(a){a.addFlex=function(h,c){function o(){m.notify(b,"stateChange")}if(h.grid)return!1;c=a.extend({height:"auto",width:"auto",striped:!0,novstripe:!1,minwidth:30,minheight:80,resizable:!0,url:!1,method:"POST",dataType:"json",errormsg:"Connection Error",usepager:!0,nowrap:!0,page:1,total:1,useRp:!0,rp:15,rpOptions:[5,10,15,20,25,30,35,40,45,50],title:!1,pagestat:"Displaying {from} to {to} of {total} items",procmsg:"Processing, please wait ...",query:"",qtype:"",nomsg:"No items",minColToggle:1,
showToggleBtn:!0,hideOnSubmit:!0,autoload:!0,blockOpacity:0.5,onToggleCol:!1,onChangeSort:!1,onSuccess:!1,showSearchOnLoad:!1,floatingSearch:!1,singleSelect:!0,navbarOnTop:!1,onError:function(c){a(".pPageStat",b.pDiv).html(this.nomsg);this.displayErrors&&a("table",b.bDiv).html('<tr><td style="white-space:normal !important;padding:4px;"><h3 style="color:red;">Error</h3>'+(c.responseText?"A dmxGrid AJAX query received the following error response from the server:<hr>"+c.responseText:"A dmxGrid AJAX query received error response from the server!")+
"</td></tr>");a(".pReload",b.pDiv).removeClass("loading");b.loading=!1;a(b.block).hide()},onSubmit:!1,displayErrors:!0,pagerLeft:"Page",pagerRight:"of {total}",searchFieldLabel:"Quick Search",searchButtonLabel:"Search",clearButtonLabel:"Clear",toggleGridTooltip:"Minimize/Maximize Table",toggleColsTooltip:"Hide/Show Columns"},c);a(h).show().attr({cellPadding:0,cellSpacing:0,border:0}).removeAttr("width");var m={internalEvents:{statechange:1},listeners:{},add:function(a,b,c,g){b=(""+b).toLowerCase();
this.listeners[b]||(this.listeners[b]=[]);this.listeners[b].push({target:a,callback:c,internal:g?!0:!!this.internalEvents[b]})},remove:function(a,b,c){if(a&&!b)for(var g in this.listeners)for(var l=0;l<this.listeners[g].length;l++)this.listeners[g][l].target&&this.listeners[g][l].target===a&&!0!=this.listeners[g][l].internal&&!this.internalEvents[g]&&this.listeners[g].splice(l,1);else if(a&&b&&(b=(""+b).toLowerCase(),this.listeners[b]))for(l=0;l<this.listeners[b].length;l++)this.listeners[b][l].target&&
this.listeners[b][l].target===a&&(c&&this.listeners[b][l].callback===c||!c)&&!this.listeners[b][l].internal&&!this.internalEvents[b]&&this.listeners[b].splice(l,1)},notify:function(d,e,f){for(var e=(""+e).toLowerCase(),d=this.listeners[e]||[],g=0;g<d.length;g++)if("function"==typeof d[g].callback&&d[g].target&&"object"==typeof d[g].target){var l={type:e,grid:b,prefs:c,target:d[g].target};f&&"object"==typeof f&&(l=a.extend(l,f));d[g].callback.call(d[g].target,l)}}},b={addEventListener:function(a,b){m.add(this,
a,b);return this},removeEventListener:function(a,b){m.remove(this,a,b);return this},hset:{},rePosDrag:function(){var d=0-this.hDiv.scrollLeft;0<this.hDiv.scrollLeft&&(d-=Math.floor(c.cgwidth/2));a(b.cDrag).css({top:b.hDiv.offsetTop+1});var e=this.cdpad;a("div",b.cDrag).hide();a("thead tr:first th:visible",this.hDiv).each(function(){var f=a("thead tr:first th:visible",b.hDiv).index(this),g=parseInt(a("div",this).outerWidth());0==d&&(d-=Math.floor(c.cgwidth/2));g=g+d+e;a("div:eq("+f+")",b.cDrag).css({left:g+
"px"}).show();d=g})},fixHeight:function(c){var c=!1,c=a(b.bDiv).height(),e=a(this.hDiv).height();a("div",this.cDrag).each(function(){a(this).height(c+e)});parseInt(a(b.nDiv).height()||1)>c?a(b.nDiv).height(c).width(200):a(b.nDiv).height("auto").width("auto");a(b.block).css({height:c,marginBottom:-1*c});a(b.rDiv).css({height:"100%"})},dragStart:function(d,e,f){if("colresize"==d){a(b.nDiv).hide();a(b.nBtn).hide();var d=a("div",this.cDrag).index(f),g=a("th:visible:eq("+d+") div",this.hDiv).width();a(f).addClass("dragging").siblings().hide();
a(f).prev().addClass("dragging").show();this.colresize={startX:e.pageX,ol:parseInt(f.style.left),ow:g,n:d};a("body").css("cursor","col-resize");m.notify(b,"columnResizeStart",{colIndex:this.colresize.n,startX:this.colresize.startX,startLeft:this.colresize.ol,originalEvent:e})}else if("vresize"==d)d=!1,a("body").css("cursor","row-resize"),f&&(d=!0,a("body").css("cursor","col-resize")),this.vresize={h:c.height,sy:e.pageY,w:c.width,sx:e.pageX,hgo:d},m.notify(b,"gridResizeStart",{startX:e.pageX,startY:e.pageY,
startHeight:c.height,startWidth:c.width,resizeDirection:d?"horizontal":"vertical",originalEvent:e});else if("colMove"==d){a(b.nDiv).hide();a(b.nBtn).hide();this.hset=a(this.hDiv).offset();this.hset.right=this.hset.left+a("table",this.hDiv).width();this.hset.bottom=this.hset.top+a("table",this.hDiv).height();this.dcol=f;this.dcoln=a("th",this.hDiv).index(f);this.colCopy=document.createElement("div");this.colCopy.className="colCopy";this.colCopy.innerHTML=f.innerHTML;if(a.browser.msie)this.colCopy.className=
"colCopy ie";a(this.colCopy).css({position:"absolute","float":"left",display:"none",textAlign:f.align});a("body").append(this.colCopy);a(this.cDrag).hide()}a("body").noSelect()},dragMove:function(d){if(this.colresize){var e=this.colresize.n,f=d.pageX-this.colresize.startX,g=this.colresize.ol+f,f=this.colresize.ow+f;if(f>c.minwidth)a("div:eq("+e+")",this.cDrag).css("left",g),this.colresize.nw=f,m.notify(b,"columnResize",{colIndex:e,newWidth:f,originalEvent:d})}else if(this.vresize){e=this.vresize;
f=d.pageY-e.sy;if(!c.defwidth)c.defwidth=c.width;if("auto"!=c.width&&!c.nohresize&&e.hgo&&(g=e.w+(d.pageX-e.sx),g>c.defwidth))this.gDiv.style.width=g+"px",c.width=g;f=e.h+f;if((f>c.minheight||c.height<c.minheight)&&!e.hgo)this.bDiv.style.height=f+"px",c.height=f,this.fixHeight(f);m.notify(b,"gridResize",{newHeight:c.height,newWidth:c.width,originalEvent:d})}else this.colCopy&&(a(this.dcol).addClass("thMove").removeClass("thOver"),d.pageX>this.hset.right||d.pageX<this.hset.left||d.pageY>this.hset.bottom||
d.pageY<this.hset.top?a("body").css("cursor","move"):a("body").css("cursor","pointer"),a(this.colCopy).css({top:d.pageY+10,left:d.pageX+20,display:"block"}))},dragEnd:function(){if(this.colresize){var b=this.colresize.n,e=this.colresize.nw;a("th:visible:eq("+b+") div",this.hDiv).css("width",e);a("tr",this.bDiv).each(function(){a("td:visible:eq("+b+") div",this).css("width",e)});this.hDiv.scrollLeft=this.bDiv.scrollLeft;a("div:eq("+b+")",this.cDrag).siblings().show();a(".dragging",this.cDrag).removeClass("dragging");
this.rePosDrag();"auto"==c.height&&a(this.bDiv).css({height:"auto"});this.fixHeight();this.colresize=!1;m.notify(this,"columnResizeEnd",{colIndex:b,newWidth:e})}else if(this.vresize)this.vresize=!1,m.notify(this,"gridResizeEnd");else if(this.colCopy)a(this.colCopy).remove(),null!=this.dcolt&&(this.dcoln>this.dcolt?a("th:eq("+this.dcolt+")",this.hDiv).before(this.dcol):a("th:eq("+this.dcolt+")",this.hDiv).after(this.dcol),this.switchCol(this.dcoln,this.dcolt),a(this.cdropleft).remove(),a(this.cdropright).remove(),
this.rePosDrag()),this.colCopy=this.dcolt=this.dcoln=this.hset=this.dcol=null,a(".thMove",this.hDiv).removeClass("thMove"),a(this.cDrag).show();a("body").css("cursor","default");a("body").noSelect(!1)},toggleCol:function(d,e){var f=a("th[axis='col"+d+"']",this.hDiv)[0],g=a("thead th",b.hDiv).index(f),l=a("input[value="+d+"]",b.nDiv)[0];if(null==e)e=f.hide;if(a("input:checked",b.nDiv).length<c.minColToggle&&!e)return!1;e?(f.hide=!1,a(f).show(),l.checked=!0):(f.hide=!0,a(f).hide(),l.checked=!1);a("tbody tr",
h).each(function(){e?a("td:eq("+g+")",this).show():a("td:eq("+g+")",this).hide()});this.rePosDrag();m.notify(this,e?"columnShow":"columnHide",{tHeader:f});if(c.onToggleCol)c.onToggleCol(d,e);return e},switchCol:function(b,c){a("tbody tr",h).each(function(){b>c?a("td:eq("+c+")",this).before(a("td:eq("+b+")",this)):a("td:eq("+c+")",this).after(a("td:eq("+b+")",this))});b>c?a("tr:eq("+c+")",this.nDiv).before(a("tr:eq("+b+")",this.nDiv)):a("tr:eq("+c+")",this.nDiv).after(a("tr:eq("+b+")",this.nDiv));
if(a.browser.msie&&7>a.browser.version)a("tr:eq("+c+") input",this.nDiv)[0].checked=!0;this.hDiv.scrollLeft=this.bDiv.scrollLeft;m.notify(this,"columnSwitch",{oldIndex:b,newIndex:c})},scroll:function(){this.hDiv.scrollLeft=this.bDiv.scrollLeft;this.rePosDrag()},addData:function(d){c.preProcess&&(d=c.preProcess(d));a(".pReload",this.pDiv).removeClass("loading");this.loading=!1;if(!d)return a(".pPageStat",this.pDiv).html(c.errormsg),!1;this.data=d;c.total="xml"==c.dataType?+a("rows total",d).text():
d.total;if(0==c.total)return a("tr, a, td, div",h).unbind(),a(h).empty(),c.pages=1,c.page=1,this.buildpager(),a(".pPageStat",this.pDiv).html(c.nomsg),!1;c.pages=Math.ceil(c.total/c.rp);c.page="xml"==c.dataType?+a("rows page",d).text():d.page;this.buildpager();var e=document.createElement("tbody");"json"==c.dataType?a.each(d.rows,function(d,g){var l=document.createElement("tr");if(d%2&&c.striped)l.className="erow";if(g.id)l.id="row"+g.id;a("thead tr:first th",b.hDiv).each(function(){function b(a){a=
a.replace(/\{([0-9]+)\}/g,function(a){a=parseInt(a.replace(/\D/g,""));return g.cell.length>a?g.cell[a]:a}).replace(/\{rowid\}/gi,"row"+g.id).replace(/\{recid\}/gi,g.id);if(c.colModel&&0<c.colModel.length){var e=a.match(/\{([a-z A-Z_0-9-]+)\}/i);if(e&&1<e.length)for(var d=0;d<e.length;d++)for(var f=0;f<c.colModel.length;f++)if(c.colModel[f].name.toLowerCase()==e[d].toLowerCase()){a=a.replace(RegExp("\\{"+e[d]+"\\}","gi"),g.cell[f]);break}}return a}var e=document.createElement("td"),d=a(this).attr("axis").substr(3);
e.align=this.align;var f="",h="",j=null,m=null,k=null,r=null,o=null,p=null,n=null;c.colModel&&c.colModel[d]&&(n=c.colModel[d],f=n.before||"",h=n.after||"",j=n.onclick||null,m=n.ondblclick||null,k=n.onmousedown||null,r=n.onmouseup||null,o=n.onmouseover||null,p=n.mouseenter||null,n=n.mouseleave||null);f&&(f=b(f));h&&(h=b(h));e.innerHTML=f+g.cell[d]+h;if(j)e.onclick=new Function(b(j));if(m)e.ondblclick=new Function(b(m));if(k)e.onmousedown=new Function(b(k));if(r)e.onmouseup=new Function(b(r));if(o)e.onmouseover=
new Function(b(o));p&&a(e).bind("mouseenter",new Function(b(p)));n&&a(e).bind("mouseleave",new Function(b(n)));a(l).append(e);e=null});if(1>a("thead",this.gDiv).length)for(idx=0;idx<cell.length;idx++){var h=document.createElement("td");h.innerHTML=g.cell[idx];a(l).append(h);h=null}a(e).append(l);l=null}):"xml"==c.dataType&&(i=1,a("rows row",d).each(function(){i++;var d=document.createElement("tr");if(i%2&&c.striped)d.className="erow";var g=a(this).attr("id");if(g)d.id="row"+g;var g=null,h=this;a("thead tr:first th",
b.hDiv).each(function(){var b=document.createElement("td"),c=a(this).attr("axis").substr(3);b.align=this.align;b.innerHTML=a("cell:eq("+c+")",h).text();a(d).append(b)});1>a("thead",this.gDiv).length&&a("cell",this).each(function(){var b=document.createElement("td");b.innerHTML=a(this).text();a(d).append(b)});a(e).append(d);h=d=null}));a("tr",h).unbind();a(h).empty();a(h).append(e);this.addCellProp();this.addRowProp();if("auto"==c.height||h.height&&"auto"==h.height)a(this.bDiv).css({height:"auto"}),
c.hideOnSubmit&&a(b.block).hide();this.fixHeight(a(this.bDiv).height());this.rePosDrag();i=d=e=null;a(this.cDrag).css({height:a(this.bDiv).height()});if(c.onSuccess)c.onSuccess();c.hideOnSubmit&&a(b.block).remove();this.hDiv.scrollLeft=this.bDiv.scrollLeft;a.browser.opera&&a(h).css("visibility","visible");m.notify(this,"contentReloaded")},changeSort:function(d){m.notify(this,"beforeChangeSort",{sortname:c.sortname||"",sortorder:c.sortorder||""});if(this.loading)return!0;a(b.nDiv).hide();a(b.nBtn).hide();
if(c.sortname==a(d).attr("abbr"))c.sortorder="asc"==c.sortorder?"desc":"asc";a(d).addClass("sorted").siblings().removeClass("sorted");a(".sdesc",this.hDiv).removeClass("sdesc");a(".sasc",this.hDiv).removeClass("sasc");a("div",d).addClass("s"+c.sortorder);c.sortname=a(d).attr("abbr");if(c.onChangeSort)c.onChangeSort(c.sortname,c.sortorder);else this.populate();m.notify(this,"afterChangeSort",{sortname:c.sortname,sortorder:c.sortorder||""})},buildpager:function(){a(".pcontrol input",this.pDiv).val(c.page);
a(".pcontrol span",this.pDiv).html(c.pages);var b=(c.page-1)*c.rp+1,e=b+c.rp-1;if(c.total<e)e=c.total;var f=c.pagestat,f=f.replace(/{from}/,b),f=f.replace(/{to}/,e),f=f.replace(/{total}/,c.total);a(".pPageStat",this.pDiv).html(f)},populate:function(){if(this.loading)return!0;if(c.onSubmit&&!c.onSubmit())return!1;this.loading=!0;if(!c.url)return!1;a(".pPageStat",this.pDiv).html(c.procmsg);a(".pReload",this.pDiv).addClass("loading");a(b.block).css({top:b.bDiv.offsetTop});c.hideOnSubmit&&a(this.gDiv).prepend(b.block);
a.browser.opera&&a(h).css("visibility","hidden");if(!c.newp)c.newp=1;if(c.page>c.pages)c.page=c.pages;var d=[{name:"page",value:c.newp},{name:"rp",value:c.rp},{name:"sortname",value:c.sortname||""},{name:"sortorder",value:c.sortorder||""},{name:"query",value:c.query},{name:"qtype",value:c.qtype}];if(document.location.search){for(var e,f=document.location.search.replace(/^\?/,""),g={},f=f.replace(/&amp;/g,"&"),f=f.split("&"),l=0;l<f.length;l++)e=f[l].split("="),/^(page|rp|sortname|sortorder|query|qtype)$/.test(decodeURIComponent(e[0]))||
(g[e[0]]=e[1]);for(var j in g)d.push({name:j,value:g[j]})}if(c.params)for(e=0;e<c.params.length;e++)d[d.length]=c.params[e];var k=this;m.notify(k,"AJAXRequest",{method:c.method,url:c.url,responseData:d,dataType:c.dataType});a.ajax({type:c.method,url:c.url,data:d,dataType:c.dataType,success:function(a,c){m.notify(k,"ajaxSuccess",{responseData:a,textStatus:c||""});b.addData(a)},error:function(a,b,e){m.notify(k,"ajaxError",{XMLHttpRequest:a,textStatus:b,errorThrown:e,requestOprions:this});try{if(c.onError)c.onError(a)}catch(d){}},
complete:function(a,b){m.notify(k,"ajaxComplete",{XMLHttpRequest:a,textStatus:b,requestOprions:this})}})},doSearch:function(){c.query=a("input[name=q]",b.sDiv).val();c.qtype=a("select[name=qtype]",b.sDiv).val();c.newp=1;this.populate()},changePage:function(b){if(this.loading)return!0;switch(b){case "first":c.newp=1;break;case "prev":if(1<c.page)c.newp=parseInt(c.page)-1;break;case "next":if(c.page<c.pages)c.newp=parseInt(c.page)+1;break;case "last":c.newp=c.pages;break;case "input":var e=parseInt(a(".pcontrol input",
this.pDiv).val());isNaN(e)&&(e=1);if(1>e)e=1;else if(e>c.pages)e=c.pages;a(".pcontrol input",this.pDiv).val(e);c.newp=e;break;default:if(isNaN(b))return!1;e=parseInt(b);if(1>e)e=1;else if(e>c.pages)e=c.pages;a(".pcontrol input",this.pDiv).val(e);c.newp=e}if(c.newp==c.page)return!1;m.notify(this,"changePageRequested",{argument:b,newPageInt:c.newp});if(c.onChangePage)c.onChangePage(c.newp);else this.populate()},addCellProp:function(){a("tbody tr td",b.bDiv).each(function(){var d=document.createElement("div"),
e=a("td",a(this).parent()).index(this),e=a("th:eq("+e+")",b.hDiv).get(0);if(null!=e){if(c.sortname==a(e).attr("abbr")&&c.sortname)this.className="sorted";a(d).css({textAlign:e.align,width:a("div:first",e)[0].style.width});e.hide&&a(this).css("display","none")}!1==c.nowrap&&a(d).css("white-space","normal");if(""==this.innerHTML)this.innerHTML="&nbsp;";d.innerHTML=this.innerHTML;var f=a(this).parent()[0],g=!1;f.id&&(g=f.id.substr(3));null!=e&&e.process&&e.process(d,g);a(this).empty().append(d).removeAttr("width")})},
getCellDim:function(b){var c=parseInt(a(b).height()),f=parseInt(a(b).parent().height()),g=parseInt(b.style.width),h=parseInt(a(b).parent().width()),j=b.offsetParent.offsetTop,k=b.offsetParent.offsetLeft,m=parseInt(a(b).css("paddingLeft")),b=parseInt(a(b).css("paddingTop"));return{ht:c,wt:g,top:j,left:k,pdl:m,pdt:b,pht:f,pwt:h}},addRowProp:function(){function d(e,d,g){function h(e){e=e.replace(/\{([0-9]+)\}/g,function(e){var g=parseInt(e.replace(/\D/g,""));return c.colModel&&c.colModel.length>g?(e=
a("thead tr:first th",b.hDiv).index(a("thead tr:first th[axis=col"+g+"]",b.hDiv)),a(d).find("td").eq(e).text()):e}).replace(/\{rowid\}/gi,d.id).replace(/\{recid\}/gi,d.id.replace(/^row(\d+)/,"$1"));if(c.colModel&&0<c.colModel.length){var g=e.match(/\{([a-z A-Z_0-9-]+)\}/i);if(g&&1<g.length)for(var j=0;j<g.length;j++)for(var l=0;l<c.colModel.length;l++)if(c.colModel[l].name.toLowerCase()==g[j].toLowerCase()){var k=a("tbody tr",b.bDiv).index(a(d));-1<k&&(e=e.replace(RegExp("\\{"+g[j]+"\\}","gi"),b.data.rows[k].cell[l]));
break}}return e}if("function"==typeof c[e])c[e].call(d,g);else if("string"==typeof c[e])try{(new Function(h(c[e]))).call(d,g)}catch(j){alert(c[e]+"\n\n"+j)}}a("tbody tr",b.bDiv).each(function(){a(this).click(function(b){var f=b.target||b.srcElement;if(f.href||f.type)return!0;a(this).toggleClass("trSelected");c.singleSelect&&!b.ctrlKey&&a(this).siblings().removeClass("trSelected");d("onrowclick",this,b)}).mousedown(function(c){if(c.shiftKey)a(this).toggleClass("trSelected"),b.multisel=!0,this.focus(),
a(b.gDiv).noSelect();d("onrowmousedown",this,c)}).mouseup(function(c){if(b.multisel)b.multisel=!1,a(b.gDiv).noSelect(!1);d("onrowmouseup",this,c)}).hover(function(c){b.multisel&&a(this).toggleClass("trSelected");d("onrowmouseover",this,c)},function(a){d("onrowmouseout",this,a)}).dblclick(function(a){d("onrowdblclick",this,a)}).bind("mouseenter",function(a){d("onmouseenter",this,a)}).bind("mouseleave",function(a){d("onmouseleave",this,a)});a.browser.msie&&7>a.browser.version&&a(this).hover(function(){a(this).addClass("trOver")},
function(){a(this).removeClass("trOver")})})},pager:0,registerButton:function(d){if("object"==typeof d){d.constructor!=Array&&(d=[d]);for(var e=[],f=0;f<d.length;f++){var g=d[f];if(g.separator)e.push('<div class="btnseparator"/>');else{var h=document.createElement("div");h.className="fbutton";h.innerHTML="<div><span>"+(g.name||"Button")+"</span></div>";g.bclass&&a("span",h).addClass(g.bclass);"function"==typeof g.onpress&&a(h).bind("click",{grid:b,prefs:c},g.onpress);a.browser.msie&&7>a.browser.version&&
a(h).hover(function(){a(this).addClass("fbOver")},function(){a(this).removeClass("fbOver")});e.push(h)}}if(0<e.length){d=a(".tDiv .tDiv2",a(b.gDiv));if(0==d.length)b.tDiv.className="tDiv",d=document.createElement("div"),d.className="tDiv2",a(b.tDiv).append(d),g=a(".mDiv",a(b.gDiv)),0<g.length?g.after(b.tDiv):a(b.gDiv).prepend(b.tDiv);a(d).siblings().remove();for(var f in e)a(d).append(e[f]);a(b.tDiv).append("<div style='clear:both'></div>");if("auto"!=c.height)b.fixHeight(a(b.bDiv).height()),c.height=
a(b.bDiv).height();b.rePosDrag()}}}};if(c.colModel){p=document.createElement("thead");tr=document.createElement("tr");for(i=0;i<c.colModel.length;i++){var j=c.colModel[i],k=document.createElement("th");k.innerHTML=j.display;j.name&&j.sortable&&a(k).attr("abbr",j.name);a(k).attr("axis","col"+i);if(j.align)k.align=j.align;j.width&&a(k).attr("width",j.width);if(j.hide)k.hide=!0;if(j.process)k.process=j.process;a(tr).append(k)}a(p).append(tr);a(h).prepend(p)}b.gDiv=document.createElement("div");b.mDiv=
document.createElement("div");b.hDiv=document.createElement("div");b.bDiv=document.createElement("div");b.vDiv=document.createElement("div");b.rDiv=document.createElement("div");b.cDrag=document.createElement("div");b.block=document.createElement("div");b.nDiv=document.createElement("div");b.nBtn=document.createElement("div");b.iDiv=document.createElement("div");b.tDiv=document.createElement("div");b.sDiv=document.createElement("div");if(c.usepager)b.pDiv=document.createElement("div");b.hTable=document.createElement("table");
b.gDiv.className="flexigrid";if("auto"!=c.width)b.gDiv.style.width=c.width+"px";a.browser.msie&&a(b.gDiv).addClass("ie");c.novstripe&&a(b.gDiv).addClass("novstripe");a(h).before(b.gDiv);a(b.gDiv).append(h);c.buttons&&b.registerButton(c.buttons);b.hDiv.className="hDiv";a(h).before(b.hDiv);b.hTable.cellPadding=0;b.hTable.cellSpacing=0;a(b.hDiv).append('<div class="hDivBox"></div>');a("div",b.hDiv).append(b.hTable);var p=a("thead:first",h).get(0);p&&a(b.hTable).append(p);p=null;if(!c.colmodel)var q=
0;a("thead tr:first th",b.hDiv).each(function(){var d=document.createElement("div");if(a(this).attr("abbr")&&(a(this).click(function(c){if(!a(this).hasClass("thOver"))return!1;c=c.target||c.srcElement;if(c.href||c.type)return!0;b.changeSort(this)}),a(this).attr("abbr")==c.sortname))this.className="sorted",d.className="s"+c.sortorder;this.hide&&a(this).hide();this.hide&&a(this).css({display:"none"});c.colmodel||a(this).attr("axis","col"+q++);a(d).css({textAlign:this.align,width:this.width+"px"});d.innerHTML=
this.innerHTML;a(this).empty().append(d).removeAttr("width").mousedown(function(a){b.dragStart("colMove",a,this);return!1}).hover(function(){!b.colresize&&!a(this).hasClass("thMove")&&!b.colCopy&&a(this).addClass("thOver");if(a(this).attr("abbr")!=c.sortname&&!b.colCopy&&!b.colresize&&a(this).attr("abbr"))a("div",this).addClass("s"+c.sortorder);else if(a(this).attr("abbr")==c.sortname&&!b.colCopy&&!b.colresize&&a(this).attr("abbr")){var e="",e="asc"==c.sortorder?"desc":"asc";a("div",this).removeClass("s"+
c.sortorder).addClass("s"+e)}if(b.colCopy){e=a("th",b.hDiv).index(this);if(e==b.dcoln)return!1;e<b.dcoln?a(this).append(b.cdropleft):a(this).append(b.cdropright);b.dcolt=e}else if(!b.colresize&&c.showToggleBtn){var e=a("th:visible",b.hDiv).index(this),e=parseInt(a("div:eq("+e+")",b.cDrag).css("left")),d=jQuery(b.nBtn).outerWidth(),d=e-d+Math.floor(c.cgwidth/2);a(b.nDiv).hide();a(b.nBtn).hide();a(b.nBtn).css({left:d,top:b.hDiv.offsetTop}).show();var g=parseInt(a(b.nDiv).width());a(b.nDiv).css({top:b.bDiv.offsetTop});
d+g>a(b.gDiv).width()?a(b.nDiv).css("left",e-g+1):a(b.nDiv).css("left",d);a(this).hasClass("sorted")?a(b.nBtn).addClass("srtd"):a(b.nBtn).removeClass("srtd")}},function(){a(this).removeClass("thOver");if(a(this).attr("abbr")!=c.sortname)a("div",this).removeClass("s"+c.sortorder);else if(a(this).attr("abbr")==c.sortname){var d="",d="asc"==c.sortorder?"desc":"asc";a("div",this).addClass("s"+c.sortorder).removeClass("s"+d)}if(b.colCopy)a(b.cdropleft).remove(),a(b.cdropright).remove(),b.dcolt=null})});
b.bDiv.className="bDiv";a(h).before(b.bDiv);a(b.bDiv).css({height:"auto"==c.height?"auto":c.height+"px"}).scroll(function(){b.scroll()}).append(h);"auto"==c.height&&a("table",b.bDiv).addClass("autoht");b.addCellProp();b.addRowProp();j=a("thead tr:first th:visible:first",b.hDiv).get(0);if(null!=j){b.cDrag.className="cDrag";b.cdpad=a(j).outerWidth()-a("div",j).outerWidth();a(b.bDiv).before(b.cDrag);var u=a(b.bDiv).height(),t=a(b.hDiv).height();a(b.cDrag).css({top:-t+"px"});a("thead tr:first th",b.hDiv).each(function(){var d=
document.createElement("div");a(b.cDrag).append(d);if(!c.cgwidth)c.cgwidth=a(d).width();a(d).css({height:u+t}).mousedown(function(a){b.dragStart("colresize",a,this);return!1});a.browser.msie&&7>a.browser.version&&(b.fixHeight(a(b.gDiv).height()),a(d).hover(function(){b.fixHeight();a(this).addClass("dragging")},function(){b.colresize||a(this).removeClass("dragging")}))})}c.striped&&a("tbody tr:odd",b.bDiv).addClass("erow");if(c.resizable&&"auto"!=c.height)b.vDiv.className="vGrip",a(b.vDiv).mousedown(function(a){b.dragStart("vresize",
a)}).html("<span></span>"),a(b.bDiv).after(b.vDiv);if(c.resizable&&"auto"!=c.width&&!c.nohresize)b.rDiv.className="hGrip",a(b.rDiv).mousedown(function(a){b.dragStart("vresize",a,!0)}).html("<span></span>").css("height",a(b.gDiv).height()),a.browser.msie&&7>a.browser.version&&a(b.rDiv).hover(function(){a(this).addClass("hgOver")},function(){a(this).removeClass("hgOver")}),a(b.gDiv).append(b.rDiv);if(c.usepager){b.pDiv.className="pDiv";b.pDiv.innerHTML='<div class="pDiv2"></div>';c.navbarOnTop?a(b.hDiv).before(b.pDiv):
a(b.bDiv).after(b.pDiv);j=' <div class="pGroup"> <div class="pFirst pButton"><span></span></div><div class="pPrev pButton"><span></span></div> </div> <div class="btnseparator"></div> <div class="pGroup"><span class="pcontrol">'+c.pagerLeft+' <input type="text" size="4" value="1" /> '+c.pagerRight.replace(/\{total\}/g,"<span> 1 </span>")+' </span></div> <div class="btnseparator"></div> <div class="pGroup"> <div class="pNext pButton"><span></span></div><div class="pLast pButton"><span></span></div> </div> <div class="btnseparator"></div> <div class="pGroup"> <div class="pReload pButton"><span></span></div> </div> <div class="btnseparator"></div> <div class="pGroup"><span class="pPageStat"></span></div>';
a("div",b.pDiv).html(j);a(".pReload",b.pDiv).click(function(){b.populate()});a(".pFirst",b.pDiv).click(function(){b.changePage("first")});a(".pPrev",b.pDiv).click(function(){b.changePage("prev")});a(".pNext",b.pDiv).click(function(){b.changePage("next")});a(".pLast",b.pDiv).click(function(){b.changePage("last")});a(".pcontrol input",b.pDiv).keydown(function(a){13==a.keyCode&&b.changePage("input")});a.browser.msie&&7>a.browser.version&&a(".pButton",b.pDiv).hover(function(){a(this).addClass("pBtnOver")},
function(){a(this).removeClass("pBtnOver")});if(c.useRp){j="";for(k=0;k<c.rpOptions.length;k++)sel=c.rp==c.rpOptions[k]?'selected="selected"':"",j+="<option value='"+c.rpOptions[k]+"' "+sel+" >"+c.rpOptions[k]+"&nbsp;&nbsp;</option>";a(".pDiv2",b.pDiv).prepend("<div class='pGroup'><select name='rp'>"+j+"</select></div> <div class='btnseparator'></div>");a("select",b.pDiv).change(function(){if(c.onRpChange)c.onRpChange(+parseInt(this.value));else c.newp=1,c.rp=+parseInt(this.value),b.populate()})}if(c.searchitems){a(".pDiv2",
b.pDiv).prepend("<div class='pGroup'> <div class='pSearch pButton'><span></span></div> </div>  <div class='btnseparator'></div>");a(".pSearch",b.pDiv).click(function(){function d(){a(b.nBtn).css({visibility:"hidden"})}function e(){if("auto"!=c.height)b.fixHeight(a(b.bDiv).height()),c.height=a(b.bDiv).height();b.rePosDrag();a(b.nBtn).css({top:b.hDiv.offsetTop,visibility:""});a(b.nDiv).css({top:b.bDiv.offsetTop})}if(c.floatingSearch){if(a(b.sDiv).css({position:c.navbarOnTop?"static":"absolute",right:0,
left:0,zIndex:c.navbarOnTop?1:0,bottom:c.navbarOnTop?0:2,overflow:"hidden"}),!a(b.sDiv).is(":animated"))if(a(b.sDiv).is(":visible"))if(c.navbarOnTop){d();a(b.sDiv).animate({height:1},"slow");var f=a(b.bDiv).height();a(b.bDiv).css({height:f}).animate({height:f+30},"slow",null,function(){a(b.sDiv).css({display:"none"});e()})}else a(b.bDiv).css({height:a(b.bDiv).height()+a(b.sDiv).outerHeight()}),"auto"!=c.height&&(c.height+=a(b.sDiv).outerHeight()),a(b.sDiv).animate({bottom:0},"slow",function(){a(b.sDiv).css({display:"none"});
"auto"!=c.height&&b.fixHeight();b.rePosDrag()});else c.navbarOnTop?(d(),a(b.sDiv).css({display:"block",height:1}).animate({height:30},"slow"),f=a(b.bDiv).height(),a(b.bDiv).css({height:f}).animate({height:f-30},"slow",null,e)):a(b.sDiv).css({display:"block"}).animate({bottom:(a(b.vDiv).height()||0)+(a(b.pDiv).outerHeight()||0)},"slow",function(){("auto"==c.height||"auto"==h.height)&&a(b.bDiv).css({height:"auto"});a(b.bDiv).css({height:a(b.bDiv).height()-a(b.sDiv).outerHeight()});a(b.sDiv).css({position:"static"});
"auto"!=c.height&&(b.fixHeight(),c.height-=a(b.sDiv).height());b.fixHeight(a(b.bDiv).height());b.rePosDrag()})}else d(),a(b.sDiv).slideToggle("slow",e)});b.sDiv.className="sDiv";sitems=c.searchitems;j="";for(k=0;k<sitems.length;k++)""==c.qtype&&!0==sitems[k].isdefault?(c.qtype=sitems[k].name,sel='selected="selected"'):sel="",j+="<option value='"+sitems[k].name+"' "+sel+" >"+sitems[k].display+"&nbsp;&nbsp;</option>";if(""==c.qtype)c.qtype=sitems[0].name;a(b.sDiv).append("<div class='sDiv2'>"+c.searchFieldLabel+
" <input type='text' size='30' name='q' class='qsbox' /> <select name='qtype'>"+j+"</select> <input type='button' name='search' value='"+c.searchButtonLabel+"'/> <input type='button' name='clear' value='"+c.clearButtonLabel+"' /></div>");a("input[name=q],select[name=qtype]",b.sDiv).keydown(function(a){13==a.keyCode&&b.doSearch()});a("input[name=search]",b.sDiv).click(function(){b.doSearch()});a("input[name=clear]",b.sDiv).click(function(){a("input[name=q]",b.sDiv).val("");c.query="";b.doSearch()});
c.navbarOnTop?a(b.pDiv).before(b.sDiv):a(b.bDiv).after(b.sDiv)}}a(b.pDiv,b.sDiv).append("<div style='clear:both'></div>");if(c.title)b.mDiv.className="mDiv",b.mDiv.innerHTML='<div class="ftitle">'+c.title+"</div>",a(b.gDiv).prepend(b.mDiv),c.showTableToggleBtn&&(a(b.mDiv).append('<div class="ptogtitle" title="'+c.toggleGridTooltip+'"><span></span></div>'),a("div.ptogtitle",b.mDiv).click(function(){a(b.gDiv).toggleClass("hideBody");a(this).toggleClass("vsble")}));b.cdropleft=document.createElement("span");
b.cdropleft.className="cdropleft";b.cdropright=document.createElement("span");b.cdropright.className="cdropright";b.block.className="gBlock";j=a(b.bDiv).height();k=b.bDiv.offsetTop;a(b.block).css({width:b.bDiv.style.width,height:j,background:"white",position:"relative",marginBottom:-1*j,zIndex:1,top:k,left:"0px"});a(b.block).fadeTo(0,c.blockOpacity);if(a("th",b.hDiv).length){b.nDiv.className="nDiv";b.nDiv.innerHTML="<table cellpadding='0' cellspacing='0'><tbody></tbody></table>";a(b.nDiv).css({marginBottom:-1*
j,display:"none",top:k}).noSelect();var s=0;a("th div",b.hDiv).each(function(){var c='checked="checked"';"none"==a("th[axis='col"+s+"']",b.hDiv)[0].style.display&&(c="");a("tbody",b.nDiv).append('<tr><td class="ndcol1"><input type="checkbox" '+c+' class="togCol" value="'+s+'" /></td><td class="ndcol2">'+this.innerHTML+"</td></tr>");s++});a.browser.msie&&7>a.browser.version&&a("tr",b.nDiv).hover(function(){a(this).addClass("ndcolover")},function(){a(this).removeClass("ndcolover")});a("td.ndcol2",b.nDiv).click(function(){return a("input:checked",
b.nDiv).length<=c.minColToggle&&a(this).prev().find("input")[0].checked?!1:b.toggleCol(a(this).prev().find("input").val())});a("input.togCol",b.nDiv).click(function(){if(a("input:checked",b.nDiv).length<c.minColToggle&&!1==this.checked)return!1;a(this).parent().next().trigger("click")});a(b.gDiv).prepend(b.nDiv);a(b.nBtn).addClass("nBtn").html("<div></div>").attr("title",c.toggleColsTooltip).click(function(){a(b.nDiv).toggle();return!0});c.showToggleBtn&&a(b.gDiv).prepend(b.nBtn)}a(b.iDiv).addClass("iDiv").css({display:"none"});
a(b.bDiv).append(b.iDiv);a(b.bDiv).hover(function(){},function(){if(b.multisel)b.multisel=!1});a(b.pDiv).bind("mouseenter",function(){a(b.nDiv).hide();a(b.nBtn).hide()});a(b.gDiv).hover(function(){},function(){a(b.nDiv).hide();a(b.nBtn).hide()});a(document).mousemove(function(a){b.dragMove(a)}).mouseup(function(){b.dragEnd()}).hover(function(){},function(){b.dragEnd()});a.browser.msie&&7>a.browser.version&&(a(".hDiv,.bDiv,.mDiv,.pDiv,.vGrip,.tDiv, .sDiv",b.gDiv).css({width:"100%"}),a(b.gDiv).addClass("ie6"),
"auto"!=c.width&&a(b.gDiv).addClass("ie6fullwidthbug"));c.showSearchOnLoad&&a(".pSearch",b.pDiv).click();b.rePosDrag();b.fixHeight();h.p=c;h.grid=b;c.url&&c.autoload&&b.populate();m.notify(b,"load");m.add(b,"contentReloaded",o,1);m.add(b,"columnSwitch",o,1);m.add(b,"columnShow",o,1);m.add(b,"columnHide",o,1);m.add(b,"columnResizeEnd",o,1);m.add(b,"gridResizeEnd",o,1);return h};var q=!1;a(document).ready(function(){q=!0});a.fn.flexigrid=function(h){return this.each(function(){if(q)a.addFlex(this,h);
else{a(this).hide();var c=this;a(document).ready(function(){a.addFlex(c,h)})}})};a.fn.flexReload=function(){return this.each(function(){this.grid&&this.p.url&&this.grid.populate()})};a.fn.flexOptions=function(h){return this.each(function(){this.grid&&a.extend(this.p,h)})};a.fn.setFilter=function(h,c,o){return this.each(function(){if(this.grid){var m=c?c.replace(/(&lt;)/gi,"<").replace(/(&gt;)/gi,">"):"",b=this.p.url.replace(/([^\/]+)\.(php|asp|jsp|cf)\?.*/,"$1.$2"),b=b+("?custom_filter_left="+encodeURIComponent(h||
"")),b=b+("&custom_filter_condition="+encodeURIComponent(m)),b=b+("&custom_filter_right="+encodeURIComponent(o||""));a.extend(this.p,{url:b,newp:1});this.grid.populate()}})};a.fn.flexToggleCol=function(a,c){return this.each(function(){this.grid&&this.grid.toggleCol(a,c)})};a.fn.flexAddData=function(a){return this.each(function(){this.grid&&this.grid.addData(a)})};a.fn.noSelect=function(h){return(prevent=null==h?!0:h)?this.each(function(){a.browser.msie||a.browser.safari?a(this).bind("selectstart",
function(){return!1}):a.browser.mozilla?(a(this).css("MozUserSelect","none"),a("body").trigger("focus")):a.browser.opera?a(this).bind("mousedown",function(){return!1}):a(this).attr("unselectable","on")}):this.each(function(){a.browser.msie||a.browser.safari?a(this).unbind("selectstart"):a.browser.mozilla?a(this).css("MozUserSelect","inherit"):a.browser.opera?a(this).unbind("mousedown"):a(this).removeAttr("unselectable","on")})}})(jQuery);
